// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/rpcpb/rpc.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcOperation int32

const (
	RpcOperation_RPC_OPERATION_UNSPECIFIED   RpcOperation = 0
	RpcOperation_RPC_OPERATION_REGISTER_NODE RpcOperation = 1
	RpcOperation_RPC_OPERATION_REGISTER      RpcOperation = 2
	RpcOperation_RPC_OPERATION_UNREGISTER    RpcOperation = 3
	RpcOperation_RPC_OPERATION_LOOKUP        RpcOperation = 4
	RpcOperation_RPC_OPERATION_DELIVER       RpcOperation = 5
)

// Enum value maps for RpcOperation.
var (
	RpcOperation_name = map[int32]string{
		0: "RPC_OPERATION_UNSPECIFIED",
		1: "RPC_OPERATION_REGISTER_NODE",
		2: "RPC_OPERATION_REGISTER",
		3: "RPC_OPERATION_UNREGISTER",
		4: "RPC_OPERATION_LOOKUP",
		5: "RPC_OPERATION_DELIVER",
	}
	RpcOperation_value = map[string]int32{
		"RPC_OPERATION_UNSPECIFIED":   0,
		"RPC_OPERATION_REGISTER_NODE": 1,
		"RPC_OPERATION_REGISTER":      2,
		"RPC_OPERATION_UNREGISTER":    3,
		"RPC_OPERATION_LOOKUP":        4,
		"RPC_OPERATION_DELIVER":       5,
	}
)

func (x RpcOperation) Enum() *RpcOperation {
	p := new(RpcOperation)
	*p = x
	return p
}

func (x RpcOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_rpcpb_rpc_proto_enumTypes[0].Descriptor()
}

func (RpcOperation) Type() protoreflect.EnumType {
	return &file_internal_rpcpb_rpc_proto_enumTypes[0]
}

func (x RpcOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcOperation.Descriptor instead.
func (RpcOperation) EnumDescriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{0}
}

type RpcEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     RpcOperation           `protobuf:"varint,1,opt,name=operation,proto3,enum=xtframework.rpc.RpcOperation" json:"operation,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcEnvelope) Reset() {
	*x = RpcEnvelope{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcEnvelope) ProtoMessage() {}

func (x *RpcEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcEnvelope.ProtoReflect.Descriptor instead.
func (*RpcEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcEnvelope) GetOperation() RpcOperation {
	if x != nil {
		return x.Operation
	}
	return RpcOperation_RPC_OPERATION_UNSPECIFIED
}

func (x *RpcEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RpcResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResult) Reset() {
	*x = RpcResult{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResult) ProtoMessage() {}

func (x *RpcResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResult.ProtoReflect.Descriptor instead.
func (*RpcResult) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RpcResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RpcResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ServiceKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceKey) Reset() {
	*x = ServiceKey{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceKey) ProtoMessage() {}

func (x *ServiceKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceKey.ProtoReflect.Descriptor instead.
func (*ServiceKey) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceKey) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ServiceLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceId     int64                  `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	NodeId        int64                  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAddr      string                 `protobuf:"bytes,4,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceLocation) Reset() {
	*x = ServiceLocation{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLocation) ProtoMessage() {}

func (x *ServiceLocation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLocation.ProtoReflect.Descriptor instead.
func (*ServiceLocation) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceLocation) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceLocation) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *ServiceLocation) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ServiceLocation) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAddr      string                 `protobuf:"bytes,2,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterNodeRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RegisterNodeRequest) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{5}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *ServiceLocation       `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetLocation() *ServiceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{7}
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *ServiceKey            `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *UnregisterRequest) GetTarget() *ServiceKey {
	if x != nil {
		return x.Target
	}
	return nil
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{9}
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *ServiceKey            `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *LookupRequest) GetTarget() *ServiceKey {
	if x != nil {
		return x.Target
	}
	return nil
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *ServiceLocation       `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *LookupResponse) GetLocation() *ServiceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *ServiceKey            `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        *ServiceKey            `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	MessageId     uint32                 `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *DeliverRequest) GetSource() *ServiceKey {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DeliverRequest) GetTarget() *ServiceKey {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DeliverRequest) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *DeliverRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DeliverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *DeliverResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_internal_rpcpb_rpc_proto protoreflect.FileDescriptor

const file_internal_rpcpb_rpc_proto_rawDesc = "" +
	"\n" +
	"\x18internal/rpcpb/rpc.proto\x12\x0fxtframework.rpc\"d\n" +
	"\vRpcEnvelope\x12;\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1d.xtframework.rpc.RpcOperationR\toperation\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"i\n" +
	"\tRpcResult\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"0\n" +
	"\n" +
	"ServiceKey\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\x89\x01\n" +
	"\x0fServiceLocation\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x03R\tserviceId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x03R\x06nodeId\x12\x1b\n" +
	"\tnode_addr\x18\x04 \x01(\tR\bnodeAddr\"K\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x1b\n" +
	"\tnode_addr\x18\x02 \x01(\tR\bnodeAddr\"\x16\n" +
	"\x14RegisterNodeResponse\"O\n" +
	"\x0fRegisterRequest\x12<\n" +
	"\blocation\x18\x01 \x01(\v2 .xtframework.rpc.ServiceLocationR\blocation\"\x12\n" +
	"\x10RegisterResponse\"H\n" +
	"\x11UnregisterRequest\x123\n" +
	"\x06target\x18\x01 \x01(\v2\x1b.xtframework.rpc.ServiceKeyR\x06target\"\x14\n" +
	"\x12UnregisterResponse\"D\n" +
	"\rLookupRequest\x123\n" +
	"\x06target\x18\x01 \x01(\v2\x1b.xtframework.rpc.ServiceKeyR\x06target\"N\n" +
	"\x0eLookupResponse\x12<\n" +
	"\blocation\x18\x01 \x01(\v2 .xtframework.rpc.ServiceLocationR\blocation\"\xb3\x01\n" +
	"\x0eDeliverRequest\x123\n" +
	"\x06source\x18\x01 \x01(\v2\x1b.xtframework.rpc.ServiceKeyR\x06source\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.xtframework.rpc.ServiceKeyR\x06target\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\rR\tmessageId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"+\n" +
	"\x0fDeliverResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload*\xbd\x01\n" +
	"\fRpcOperation\x12\x1d\n" +
	"\x19RPC_OPERATION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRPC_OPERATION_REGISTER_NODE\x10\x01\x12\x1a\n" +
	"\x16RPC_OPERATION_REGISTER\x10\x02\x12\x1c\n" +
	"\x18RPC_OPERATION_UNREGISTER\x10\x03\x12\x18\n" +
	"\x14RPC_OPERATION_LOOKUP\x10\x04\x12\x19\n" +
	"\x15RPC_OPERATION_DELIVER\x10\x05B\x1cZ\x1axtframework/internal/rpcpbb\x06proto3"

var (
	file_internal_rpcpb_rpc_proto_rawDescOnce sync.Once
	file_internal_rpcpb_rpc_proto_rawDescData []byte
)

func file_internal_rpcpb_rpc_proto_rawDescGZIP() []byte {
	file_internal_rpcpb_rpc_proto_rawDescOnce.Do(func() {
		file_internal_rpcpb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpcpb_rpc_proto_rawDesc), len(file_internal_rpcpb_rpc_proto_rawDesc)))
	})
	return file_internal_rpcpb_rpc_proto_rawDescData
}

var file_internal_rpcpb_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_rpcpb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_rpcpb_rpc_proto_goTypes = []any{
	(RpcOperation)(0),            // 0: xtframework.rpc.RpcOperation
	(*RpcEnvelope)(nil),          // 1: xtframework.rpc.RpcEnvelope
	(*RpcResult)(nil),            // 2: xtframework.rpc.RpcResult
	(*ServiceKey)(nil),           // 3: xtframework.rpc.ServiceKey
	(*ServiceLocation)(nil),      // 4: xtframework.rpc.ServiceLocation
	(*RegisterNodeRequest)(nil),  // 5: xtframework.rpc.RegisterNodeRequest
	(*RegisterNodeResponse)(nil), // 6: xtframework.rpc.RegisterNodeResponse
	(*RegisterRequest)(nil),      // 7: xtframework.rpc.RegisterRequest
	(*RegisterResponse)(nil),     // 8: xtframework.rpc.RegisterResponse
	(*UnregisterRequest)(nil),    // 9: xtframework.rpc.UnregisterRequest
	(*UnregisterResponse)(nil),   // 10: xtframework.rpc.UnregisterResponse
	(*LookupRequest)(nil),        // 11: xtframework.rpc.LookupRequest
	(*LookupResponse)(nil),       // 12: xtframework.rpc.LookupResponse
	(*DeliverRequest)(nil),       // 13: xtframework.rpc.DeliverRequest
	(*DeliverResponse)(nil),      // 14: xtframework.rpc.DeliverResponse
}
var file_internal_rpcpb_rpc_proto_depIdxs = []int32{
	0, // 0: xtframework.rpc.RpcEnvelope.operation:type_name -> xtframework.rpc.RpcOperation
	4, // 1: xtframework.rpc.RegisterRequest.location:type_name -> xtframework.rpc.ServiceLocation
	3, // 2: xtframework.rpc.UnregisterRequest.target:type_name -> xtframework.rpc.ServiceKey
	3, // 3: xtframework.rpc.LookupRequest.target:type_name -> xtframework.rpc.ServiceKey
	4, // 4: xtframework.rpc.LookupResponse.location:type_name -> xtframework.rpc.ServiceLocation
	3, // 5: xtframework.rpc.DeliverRequest.source:type_name -> xtframework.rpc.ServiceKey
	3, // 6: xtframework.rpc.DeliverRequest.target:type_name -> xtframework.rpc.ServiceKey
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_rpcpb_rpc_proto_init() }
func file_internal_rpcpb_rpc_proto_init() {
	if File_internal_rpcpb_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpcpb_rpc_proto_rawDesc), len(file_internal_rpcpb_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_rpcpb_rpc_proto_goTypes,
		DependencyIndexes: file_internal_rpcpb_rpc_proto_depIdxs,
		EnumInfos:         file_internal_rpcpb_rpc_proto_enumTypes,
		MessageInfos:      file_internal_rpcpb_rpc_proto_msgTypes,
	}.Build()
	File_internal_rpcpb_rpc_proto = out.File
	file_internal_rpcpb_rpc_proto_goTypes = nil
	file_internal_rpcpb_rpc_proto_depIdxs = nil
}
